class USCities {
  static const List<String> list = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Indianapolis",
    "Charlotte",
    "San Francisco",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Detroit",
    "Nashville",
    "Portland",
    "Memphis",
    "Oklahoma City",
    "Las Vegas",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Mesa",
    "Atlanta",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Miami",
    "Long Beach",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Tampa",
    "Arlington",
    "New Orleans",
    "Wichita",
    "Cleveland",
    "Bakersfield",
    "Aurora",
    "Anaheim",
    "Honolulu",
    "Santa Ana",
    "Riverside",
    "Corpus Christi",
    "Lexington",
    "Henderson",
    "Stockton",
    "St. Paul",
    "Cincinnati",
    "St. Louis",
    "Pittsburgh",
    "Greensboro",
    "Lincoln",
    "Anchorage",
    "Plano",
    "Orlando",
    "Irvine",
    "Newark",
    "Durham",
    "Chula Vista",
    "Toledo",
    "Fort Wayne",
    "Jersey City",
    "St. Petersburg",
    "Laredo",
    "Madison",
    "Chandler",
    "Buffalo",
    "Lubbock",
    "Scottsdale",
    "Reno",
    "Glendale",
    "Gilbert",
    "Winston-Salem",
    "North Las Vegas",
    "Norfolk",
    "Chesapeake",
    "Garland",
    "Irving",
    "Hialeah",
    "Fremont",
    "Boise",
    "Richmond",
    "Baton Rouge",
    "Spokane",
    "Des Moines",
    "Tacoma",
    "San Bernardino",
    "Modesto",
    "Fontana",
    "Santa Clarita",
    "Birmingham",
    "Oxnard",
    "Fayetteville",
    "Moreno Valley",
    "Rochester",
    "Yonkers",
    "Huntington Beach",
    "Salt Lake City",
    "Amarillo",
    "Montgomery",
    "Mobile",
    "Little Rock",
    "Huntsville",
    "Knoxville",
    "Grand Rapids",
    "Providence",
    "Tallahassee",
    "Brownsville",
    "Overland Park",
    "Tempe",
    "McKinney",
    "Cape Coral",
    "Shreveport",
    "Frisco",
    "Worcester",
    "Sioux Falls",
    "Peoria",
    "Vancouver",
    "Ontario",
    "Chattanooga",
    "Fort Lauderdale",
    "Springfield",
    "Salem",
    "Santa Rosa",
    "Oceanside",
    "Elk Grove",
    "Garden Grove",
    "Pembroke Pines",
    "Eugene",
    "Cary",
    "Fort Collins",
    "Corona",
    "Hayward",
    "Lancaster",
    "Palmdale",
    "Salinas",
    "Alexandria",
    "Lakewood",
    "Sunnyvale",
    "Pasadena",
    "Macon",
    "Pomona",
    "Clarksville",
    "Escondido",
    "Joliet",
    "Rockford",
    "Torrance",
    "Naperville",
    "Paterson",
    "Savannah",
    "Bridgeport",
    "Mesquite",
    "Killeen",
    "Syracuse",
    "McAllen",
    "Denton",
    "Waco",
    "Surprise",
    "Roseville",
    "Thornton",
    "Miramar",
    "West Valley City",
    "Olathe",
    "Hampton",
    "Warren",
    "Midland",
    "Charleston",
    "Columbia",
    "Gainesville",
    "Cedar Rapids",
    "Visalia",
    "Coral Springs",
    "Sandy Springs",
    "Carrollton",
    "Hartford",
    "New Haven",
    "Stamford",
    "Round Rock",
    "Kent",
    "Bellevue",
    "Sterling Heights",
    "Concord",
    "Elizabeth",
    "Thousand Oaks",
    "Lafayette",
    "Athens",
    "Topeka",
    "Simi Valley",
    "Fargo",
    "Abilene",
    "Norman",
    "Wilmington",
    "Evansville",
    "Greeley",
    "Provo",
    "Pearland",
    "Vallejo",
    "Ann Arbor",
    "Berkeley",
    "Allentown",
    "Erie",
    "Clearwater",
    "Victorville",
    "Federal Way",
    "Temecula",
    "Pueblo",
    "Gresham",
    "Meridian",
    "High Point",
    "Billings",
    "Norwalk",
    "Inglewood",
    "Brockton",
    "Odessa",
    "Carlsbad",
    "Elgin",
    "Davenport",
    "Manchester",
    "League City",
    "Tuscaloosa",
    "South Bend",
    "Lewisville",
    "Murfreesboro",
    "Tyler",
    "West Jordan",
    "Lowell",
    "Lakeland",
    "San Mateo",
    "Rialto",
    "Boulder",
    "Allen",
    "El Monte",
    "Augusta",
    "Waukegan",
    "Hillsboro",
    "Longmont",
    "Sioux City",
    "Burbank",
    "Vista",
    "Miami Beach",
    "Santa Monica",
    "Santa Barbara",
    "Ventura",
    "Santa Maria",
    "Arvada",
    "Cambridge",
    "Everett",
    "Fall River",
    "New Bedford",
    "Quincy",
    "Somerville",
    "Haverhill",
    "Lynn",
    "Newton",
    "Newport News",
    "New Rochelle",
    "White Plains",
    "Mount Vernon",
    "Poughkeepsie",
    "Troy",
    "Albany",
    "Schenectady",
    "Utica",
    "Rochester Hills",
    "Dearborn",
    "Livonia",
    "Farmington Hills",
    "Canton",
    "Novi",
    "Annandale",
    "Arlington Heights",
    "Evanston",
    "Cicero",
    "Berwyn",
    "Skokie",
    "Oak Park",
    "Downers Grove",
    "Schaumburg",
    "Des Plaines",
    "Palatine",
    "Orland Park",
    "Tinley Park",
    "Bolingbrook",
    "Plainfield",
    "Naples",
    "Sarasota",
    "Fort Myers",
    "Port St. Lucie",
    "Palm Bay",
    "Melbourne",
    "Daytona Beach",
    "Deltona",
    "Kissimmee",
    "Ocala",
    "Pensacola",
    "Panama City",
  ];
}
